import "./globals.css"
import ToggleTheme from "./themeswitcher.js";
import Provider from "./provider"

export const metadata = {
  title: "Hexleap Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Provider>
        <ToggleTheme/>
          {children}
        </Provider>
      </body>
    </html>
  )
}
